[project]
name = "with-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "rsconnect>=1.27.1",
]

[project.scripts]
with-connect = "main:main"

[tool.setuptools]
py-modules = ["main"]
